#pragma once

#define WM_VIEW_DB_CLICK    (WM_USER + 101)
#define WM_SNAP_IMG         (WM_USER + 102)
#define WM_VIEW_RESIZE      (WM_USER + 103)
#define WM_VIEW_RESIZE_STOP (WM_USER + 104)
#define WM_UPDATE_PATIENT_INFO (WM_USER + 105)
#define WM_IMG_VALID_RECT_SELECT_FINISH (WM_USER + 106)
#define WM_TRIANGLE_VERTEXES_SELECT_FINISH (WM_USER + 107)
#define WM_IMGRECT_SELECT_TIPS_CLOSE (WM_USER + 108)
#define WM_IMGRECT_SCALE_CLOSE (WM_USER + 109)

#define SNAP_IMG_VIEW (0)
#define GRAB_DIV_VIEW (1)
#define VIEW_MAX_SIZE (1)
#define VIEW_NORMAL_SIZE (0)
#define VIEW_MIN_SIZE (-1)